import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://msydhfyerbwrlyegtfav.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zeWRoZnllcmJ3cmx5ZWd0ZmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDQ5NjkzODQsImV4cCI6MjAyMDU0NTM4NH0.qYAZVb5bvIumtrDhvYZf_A0MtZnyCLOtQWTaWy3pb1Y')